[package]
name = "crowdfund"
version = "1.0.0"
authors = []

[addresses]
# crowdfund_addr = '0x80fc7c711b3eeef9dc4d46cf2682196478a7dc5c6efaa49af7a5bffdb91c657a'
crowdfund_addr = '_'

[dev-addresses]
crowdfund_addr = '0x111'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]